### ISSUE TITLE
still get "can't find card-tools" despite everything I've tried

### ISSUE THREAD

**Issue by evanrich** [custom-cards/secondaryinfo-entity-row#13]
Ok maybe I'm dense, but I can't get this to work, it always says "can't find card tools:

things I've tried

using card-tools 0.4 and 0.4.1
using "raw editor" in lovelace ui, as well as editing /configdir/ui-lovelace.yaml

config_dir/ui-lovelace.yaml:
```
resources:
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module
  - url: /local/card-tools.js
    type: js
  - url: /local/secondaryinfo-entity-row.js
    type: module
```

UI:
![image](https://user-images.githubusercontent.com/518320/61023070-3cde5300-a35d-11e9-8b9e-887ebbf3f7e1.png)

www directory:
```
/home-assistant/config/www$ ls -la
total 694
drwxr-xr-x  5 1001 1001     13 Jul 10 21:50 .
drwxr-xr-x 10 1001 1001     48 Jul 10 21:54 ..
-rw-r--r--  1 root 1001  11852 Jul 10 21:50 card-tools.js
drwxr-xr-x  3 root 1001      3 Feb  9 15:03 custom-lovelace
drwxr-xr-x  2 root 1001      4 Feb  9 14:40 custom_ui
-rw-r--r--  1 root 1001     54 Aug 30  2018 googlee25d310138468eb5.html
-rw-r--r--  1 root 1001 175658 Aug 19  2018 lifx.png
-rw-r--r--  1 1001 1001  26007 May 28  2018 model-s.jpg
drwxr-xr-x  2 root 1001      7 Feb  9 19:09 nest-icons
-rw-r--r--  1 1001 1001  34802 Oct 28  2016 nest.jpg
-rw-r--r--  1 root 1001  21011 Aug 13  2018 nest.png
-rw-r--r--  1 root 1001 326811 Dec 22  2016 nestprotectg2.png
-rw-r--r--  1 root 1001   2146 Jul 10 21:34 secondaryinfo-entity-row.js
```

Despite this, everything still says "can't find card tools":
![image](https://user-images.githubusercontent.com/518320/61023136-7e6efe00-a35d-11e9-8b1d-1acbef98b4a4.png)

What am I missing?
