### ISSUE TITLE
Secondary info does not appear immediately

### ISSUE THREAD

**Issue by queimadus** [custom-cards/secondaryinfo-entity-row#30]
This seems to coincide with the home assistant 0.110 update (currently on 0.110.4).
It takes a few ticks to `_updateElement` for the information to update.

![Screen Recording 2020-05-31 at 12 27 27 mov](https://user-images.githubusercontent.com/1107697/83351282-84d1e400-a33a-11ea-9950-d78bd9e018f2.gif)

Error details:
```
secondaryinfo-entity-row.js:39 Uncaught (in promise) TypeError: Cannot read property 'shadowRoot' of null
    at HTMLElement._updateElement (secondaryinfo-entity-row.js:39)
```
<img width="1118" alt="Screenshot 2020-05-31 at 12 10 30" src="https://user-images.githubusercontent.com/1107697/83350986-23107a80-a338-11ea-8c95-1f168c03712e.png">

**Comment by cstotts** [comment]
I get the following error in my frontend until I reload at least once. 

It also shows this on my mobile device.

`r.setConfig is not a function
entity: lock.front_door
name: Front Door
secondary_info: >-
  <b style="[[ if(lock.front_door.state == "locked","color:green","color:red")
  ]]">[[ {entity}.attributes.lock_status ]]</b>
type: 'custom:secondaryinfo-entity-row'`

**Comment by Ndrinta** [comment]
Same here!

r.setConfig is not a function
bla bla bla...

Takes a few seconds to get the value.
To be fair it's a tricky one because the secondary entity it's a generic sensor getting info from another history_stat sensor so fair enough that takes a sec to update but the error is unbearable.
A giant red square in the middle of you home...

Card
```
entities:
  - entity: climate.furnace
    hold_action:
      action: more-info
    secondary_info: 'Active for [[ sensor.furnace_on_time ]] '
    tap_action:
      action: navigate
      navigation_path: /lovelace/furnace
    type: 'custom:secondaryinfo-entity-row'
    state_color: true
type: entities
```
Sensors
```
  - platform: history_stats
    name: Furnace ON time raw
    entity_id: sensor.furnace_operation_mode
    state: 'Heating'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  - platform: template
    sensors:
      furnace_on_time:
        friendly_name: Furnace ON time
        value_template: >-
          {{ state_attr('sensor.furnace_on_time_raw', 'value') }}
```
Happy to share more if can help!
