### ISSUE TITLE
Custom element doesnt exist

### ISSUE THREAD

**Issue by alnavasa** [custom-cards/secondaryinfo-entity-row#39]
Tried using it, getting error, so to diagnose I used the exact same text as in GitHub and I still get an error. Installed from HACS did a couple of restarts

```
type: entities
title: Custom Secondary Info
entities:
  - entity: sun.sun
    name: Entity ID with wrapped in tag
    type: 'custom:secondaryinfo-entity-row'
    secondary_info: '<b style=''color:red''>[[ sun.sun.entity_id ]]</b>'
  - entity: sun.sun
    name: Absolute time for last-changed
    type: 'custom:secondaryinfo-entity-row'
    secondary_info: '[[ sun.sun.last_changed ]]'
  - entity: sun.sun
    name: Static text
    type: 'custom:secondaryinfo-entity-row'
    secondary_info: This is the entity row for the Sun
  - entity: sun.sun
    name: Entity attribute
    type: 'custom:secondaryinfo-entity-row'
    secondary_info: 'Next Dawn: [[ sun.sun.attributes.next_dawn ]]'
  - entity: sun.sun
    name: Templated entity object
    type: 'custom:secondaryinfo-entity-row'
    secondary_info: 'Next Dawn: [[ {entity}.attributes.next_dawn ]]'
  - entity: sun.sun
    name: Conditional template
    type: 'custom:secondaryinfo-entity-row'
    secondary_info: '[[ if(sun.sun.attributes.elevation < 0, "Below", "Above") ]] the horizon'
```

<img width="468" alt="Captura de pantalla 2020-12-18 a las 10 05 06" src="https://user-images.githubusercontent.com/458370/102608814-c7b6a600-412a-11eb-8fa4-421c13c258fd.png">
