### ISSUE TITLE
jinja2 example not working? 

### ISSUE THREAD

**Issue by JonGilmore** [custom-cards/secondaryinfo-entity-row#43]
I seem be having issues using jinja2 from the latest 5.0 release. yml is copied directly out of the readme: 
```yaml
      - entity: sun.sun
        name: Jinja2 template
        type: "custom:secondaryinfo-entity-row"
        secondary_info: "Next Dawn: {{ state_attr('sun.sun', 'next_dawn') }}"
```

![image](https://user-images.githubusercontent.com/7232986/115932658-f800af00-a452-11eb-832d-0de854bd0c6e.png)

Thoughts on what may be going on?
