### ISSUE TITLE
Referencing current item Problem

### ISSUE THREAD

**Issue by advokatb** [custom-cards/secondaryinfo-entity-row#8]
Hi. I have a card for my packages (using 17track)
```
      - card:
          type: custom:auto-entities
          show_empty: false
          card:
            type: entities
            title: PACKAGES
            show_header_toggle: false
          filter:
            include:
              - entity_id: 'sensor.*track_package_*'
                options:
                  secondary_info: "<span style='color:grey'>[[ {entity}.attributes.info_text ]]</span>" 
        style:
          background-blend-mode: multiply
          background-color: 'rgba(180,180,180,0.5)'
          # background-image: url("/local/images/grey_theme/salon.png")
          background-position: 250px -50%
          background-repeat: no-repeat
          background-size: 70% auto
          border-radius: 10px
          font-weight: 600
          color: 'rgba(100,100,100,1)'
          box-shadow: >-
            -5px 5px 13px -7px #999999, 5px 5px 13px -7px #999999, 0px 2px 0px
            0px rgba(90,90,90,0.5), 0px 0px 1px 1px rgba(0,0,0,0.1)
        type: 'custom:card-modder'  
```

But `secondary_info: "<span style='color:grey'>[[ {entity}.attributes.info_text ]]</span>"` doesn't show nothing in second row
![изображение](https://user-images.githubusercontent.com/6189889/55145504-7f33a980-514b-11e9-97a7-a6d789f884f6.png)

Please help to solve this.
Thanks.
